-- Tabela GENERO
CREATE TABLE GENERO (
    ID_GENERO SERIAL PRIMARY KEY,
    NOME_GENERO TEXT NOT NULL
);

-- Tabela FILMES
CREATE TABLE FILMES (
    ID_FILME SERIAL PRIMARY KEY,
    TITULO_FILME TEXT NOT NULL,
    DURACAO_FILME INT,
    SINOPSE_FILME TEXT,
    DATA_LANCAMENTO DATE,
    ID_GENERO INT NOT NULL,
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO)
);

-- Tabela SERIES
CREATE TABLE SERIES (
    ID_SERIE SERIAL PRIMARY KEY,
    TITULO_SERIE TEXT NOT NULL,
    SINOPSE_SERIE TEXT,
    DATA_LANCAMENTO DATE,
    ID_GENERO INT NOT NULL,
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO)
);

-- Tabela TEMPORADAS
CREATE TABLE TEMPORADAS (
    ID_TEMPORADA SERIAL PRIMARY KEY,
    NUMERO_TEMPORADA INT NOT NULL,
    ID_SERIE INT NOT NULL,
    FOREIGN KEY (ID_SERIE) REFERENCES SERIES(ID_SERIE)
);

-- Tabela EPISODIOS
CREATE TABLE EPISODIOS (
    ID_EPISODIO SERIAL PRIMARY KEY,
    DURACAO_EPISODIO INT,
    NUMERO_EPISODIO INT NOT NULL,
    TITULO_EPISODIO TEXT NOT NULL,
    ID_TEMPORADA INT NOT NULL,
    FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADAS(ID_TEMPORADA)
);